In [1]:
import numpy as np
import pandas as pd


In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
c=load_breast_cancer()

In [4]:
c.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
c.data


array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [6]:
c.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
c.target_names

array(['malignant', 'benign'], dtype='<U9')

In [8]:
c.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [9]:
df=pd.DataFrame(np.c_[c.data,c.target],columns=list(c.feature_names)+["output"])
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,output
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0.0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0.0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0.0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0.0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0.0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0.0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0.0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0.0


In [10]:
df.isnull().sum().sum()

np.int64(0)

In [11]:
cat_col=df.select_dtypes(include=["object"]).columns.tolist()
cat_col

[]

In [12]:
x=df.iloc[:, :-1]

In [13]:
x.shape

(569, 30)

In [14]:
x

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [15]:
y=df.iloc[:, -1]
y

,output
0,0.0
1,0.0
2,0.0
3,0.0
4,0.0
...,...
564,0.0
565,0.0
566,0.0
567,0.0


In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=41)

#Don't change the values multiple time = random_state=41

In [18]:
x_train.shape

(455, 30)

In [19]:
y_train.shape

(455,)

In [20]:
x_test.shape

(114, 30)

In [21]:
y_test.shape

(114,)

In [22]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [23]:
std=StandardScaler()
mm=MinMaxScaler()

In [24]:
x_train_std_sc_data=std.fit_transform(x_train)
x_train_std_sc_data

array([[-0.36498729, -0.83463794, -0.37044213, ..., -0.25967334,
         0.17192889, -0.3532633 ],
       [ 0.05208811, -0.26700868, -0.01772895, ..., -0.60430302,
        -0.44112743, -0.4234167 ],
       [-0.12582517, -1.43250975, -0.15915297, ..., -0.52384354,
        -0.86529613,  0.15674078],
       ...,
       [-0.09665906,  1.03574702, -0.1312069 , ..., -0.82212489,
        -0.39639089, -1.17784414],
       [ 1.77288871,  0.07961739,  1.6708907 , ...,  0.4236204 ,
         0.25311743, -1.39387207],
       [-0.76747963,  0.38436917, -0.75491221, ..., -0.81891263,
        -0.2323569 ,  0.23079159]])

In [25]:
df_std=pd.DataFrame(x_train_std_sc_data,columns=list(c.feature_names))
df_std

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,-0.364987,-0.834638,-0.370442,-0.422655,-0.414374,-0.408926,-0.380271,-0.456438,-0.379767,-0.534265,...,-0.453655,-1.061777,-0.419853,-0.488824,-0.003816,0.029583,0.347072,-0.259673,0.171929,-0.353263
1,0.052088,-0.267009,-0.017729,-0.046333,-2.194288,-0.994345,-0.811747,-0.902450,-0.639652,-1.012387,...,-0.004653,-0.093985,-0.036730,-0.101754,-1.670457,-0.251139,-0.569570,-0.604303,-0.441127,-0.423417
2,-0.125825,-1.432510,-0.159153,-0.237774,0.023381,-0.324060,-0.630296,-0.591236,-1.660629,0.095920,...,-0.190156,-1.553042,-0.222201,-0.307142,-0.069345,-0.056598,-0.476515,-0.523844,-0.865296,0.156741
3,-0.951226,1.138106,-0.963237,-0.855932,-1.026942,-0.728996,-0.930789,-1.048503,0.626360,0.072526,...,-0.677102,0.919659,-0.703694,-0.670145,-0.536791,-0.589527,-1.023143,-1.256851,0.259745,-0.451255
4,1.901220,2.329197,2.051973,1.837960,1.564913,3.321893,3.382945,2.716423,2.189384,1.078482,...,2.002153,2.224786,2.363120,1.710186,1.411628,3.876684,3.182380,2.297439,1.963047,2.206779
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,-0.717897,-0.264682,-0.646092,-0.715184,1.543242,0.850809,0.180262,0.194258,0.555820,1.427935,...,-0.607538,-0.071059,-0.574565,-0.629429,1.979553,0.199411,0.207969,0.409854,-0.401362,0.464079
451,-0.359154,0.477423,-0.381451,-0.399992,-1.489979,-0.399902,-0.342902,-0.773410,-0.843848,-0.240374,...,-0.388307,0.192587,-0.468277,-0.416441,-1.689242,-0.397520,-0.438621,-0.899372,-0.686350,-0.158950
452,-0.096659,1.035747,-0.131207,-0.174855,-1.134574,-0.689635,-0.526408,-0.648558,-0.127307,-1.241943,...,-0.259720,0.082871,-0.274279,-0.307504,-1.704096,-0.710561,-0.668381,-0.822125,-0.396391,-1.177844
453,1.772889,0.079617,1.670891,1.864797,-1.151189,-0.352285,0.353623,0.760148,0.448153,-1.728838,...,1.437211,-0.459158,1.315470,1.413414,-1.192090,-0.650361,-0.070238,0.423620,0.253117,-1.393872


In [26]:
x_train_std_sc_data

array([[-0.36498729, -0.83463794, -0.37044213, ..., -0.25967334,
         0.17192889, -0.3532633 ],
       [ 0.05208811, -0.26700868, -0.01772895, ..., -0.60430302,
        -0.44112743, -0.4234167 ],
       [-0.12582517, -1.43250975, -0.15915297, ..., -0.52384354,
        -0.86529613,  0.15674078],
       ...,
       [-0.09665906,  1.03574702, -0.1312069 , ..., -0.82212489,
        -0.39639089, -1.17784414],
       [ 1.77288871,  0.07961739,  1.6708907 , ...,  0.4236204 ,
         0.25311743, -1.39387207],
       [-0.76747963,  0.38436917, -0.75491221, ..., -0.81891263,
        -0.2323569 ,  0.23079159]])

In [27]:
x_train_mm_sc_data=mm.fit_transform(x_train)
x_train_mm_sc_data

array([[0.28899649, 0.20358471, 0.28269829, ..., 0.33618557, 0.34236161,
        0.15072806],
       [0.35965216, 0.28610078, 0.34292531, ..., 0.25876289, 0.25445474,
        0.1424636 ],
       [0.32951233, 0.1166723 , 0.31877666, ..., 0.27683849, 0.19363269,
        0.21080939],
       ...,
       [0.33445328, 0.47548191, 0.32354855, ..., 0.20982818, 0.26086957,
        0.05358783],
       [0.65116854, 0.33648969, 0.6312631 , ..., 0.48969072, 0.35400333,
        0.02813853],
       [0.2208113 , 0.38079134, 0.21704866, ..., 0.21054983, 0.28439059,
        0.21953299]])

In [28]:
df_mm=pd.DataFrame(x_train_mm_sc_data,columns=list(c.feature_names))
df_mm

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,0.288996,0.203585,0.282698,0.172514,0.410231,0.194191,0.136715,0.152982,0.349404,0.200262,...,0.244444,0.208594,0.239309,0.129543,0.363283,0.221436,0.277636,0.336186,0.342362,0.150728
1,0.359652,0.286101,0.342925,0.232423,0.142609,0.100669,0.057990,0.068290,0.311484,0.128849,...,0.328968,0.376779,0.309632,0.195423,0.093385,0.178161,0.125000,0.258763,0.254455,0.142464
2,0.329512,0.116672,0.318777,0.201946,0.476051,0.207748,0.091097,0.127386,0.162514,0.294387,...,0.294048,0.123221,0.275588,0.160466,0.352671,0.208151,0.140495,0.276838,0.193633,0.210809
3,0.189683,0.490362,0.181476,0.103537,0.318128,0.143059,0.036270,0.040557,0.496208,0.290893,...,0.202381,0.552931,0.187210,0.098682,0.276972,0.125996,0.049473,0.112165,0.354954,0.139184
4,0.672909,0.663510,0.696334,0.532400,0.707831,0.790197,0.823336,0.755467,0.724269,0.441144,...,0.706746,0.779738,0.750126,0.503819,0.592501,0.814493,0.749760,0.910653,0.599192,0.452315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,0.229211,0.286439,0.235630,0.125944,0.704573,0.395436,0.238988,0.276541,0.485915,0.493339,...,0.215476,0.380763,0.210912,0.105612,0.684471,0.247616,0.254473,0.486598,0.260157,0.247016
451,0.289985,0.394319,0.280818,0.176122,0.248507,0.195632,0.143533,0.092793,0.281690,0.244158,...,0.256746,0.426579,0.230421,0.141863,0.090343,0.155595,0.146805,0.192474,0.219292,0.173619
452,0.334453,0.475482,0.323549,0.211963,0.301944,0.149347,0.110052,0.116501,0.386241,0.094562,...,0.280952,0.407513,0.266029,0.160404,0.087938,0.107338,0.108546,0.209828,0.260870,0.053588
453,0.651169,0.336490,0.631263,0.536672,0.299446,0.203239,0.270619,0.383996,0.470206,0.021839,...,0.600397,0.313318,0.557829,0.453308,0.170852,0.116618,0.208147,0.489691,0.354003,0.028139


In [29]:
x_test_std_sc_data=std.transform(x_test)
x_test_std_sc_data

array([[-0.43790257, -0.21350264, -0.50001024, ..., -1.62194722,
        -0.65818251, -1.11659911],
       [ 0.19791867, -1.06494654,  0.13682124, ...,  0.15746166,
         0.34259051, -0.13890569],
       [ 0.16291934, -0.94862907,  0.17492951, ...,  0.38079026,
         0.41218069,  0.02033139],
       ...,
       [-0.16665773, -0.09951152, -0.14983761, ...,  0.46645055,
        -0.39142016, -0.41784897],
       [-0.88122747, -0.51127537, -0.86330905, ..., -0.30082087,
        -0.20253254,  1.80590246],
       [-0.06165972, -0.72297317, -0.13205375, ..., -0.90625553,
        -0.89512049, -0.73687991]])

In [30]:
x_test_mm_sc_data=mm.transform(x_test)
x_test_mm_sc_data

array([[0.2766441 , 0.29387893, 0.26057407, ..., 0.03014433, 0.22333096,
        0.06080283],
       [0.38435693, 0.17010484, 0.36931531, ..., 0.42989691, 0.36683298,
        0.17598059],
       [0.37842779, 0.18701387, 0.37582243, ..., 0.48006873, 0.37681159,
        0.1947396 ],
       ...,
       [0.32259499, 0.31044978, 0.32036729, ..., 0.49931271, 0.26158232,
        0.14311951],
       [0.20154158, 0.25059182, 0.19853951, ..., 0.32694158, 0.28866714,
        0.40508986],
       [0.34038243, 0.21981738, 0.32340395, ..., 0.19092784, 0.18935614,
        0.10553588]])

**Reasoning**:
Now that both `x_test_std_sc_data` and `x_test_mm_sc_data` have been created, I will convert `x_test_std_sc_data` into a pandas DataFrame using the original feature names (`c.feature_names`).



In [31]:
df_std_test = pd.DataFrame(x_test_std_sc_data, columns=list(c.feature_names))
df_std_test

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,-0.437903,-0.213503,-0.500010,-0.476032,-0.881746,-1.187116,-1.105690,-1.185552,-0.409468,-0.619069,...,-0.578026,-0.450970,-0.653138,-0.564284,-1.261988,-1.204582,-1.293487,-1.621947,-0.658183,-1.116599
1,0.197919,-1.064947,0.136821,0.059824,-0.533565,-0.502816,-0.537837,-0.338653,-1.062894,-0.535727,...,0.216686,-1.294309,0.219092,0.008812,-0.466893,-0.351261,-0.288486,0.157462,0.342591,-0.138906
2,0.162919,-0.948629,0.174930,0.009728,1.232624,0.574324,0.150213,0.586874,1.146130,0.098844,...,0.020643,-1.243545,0.072908,-0.130888,-0.217880,0.333118,-0.071197,0.380790,0.412181,0.020331
3,-0.417486,-0.267009,-0.378911,-0.486170,0.828098,0.564724,-0.100069,0.066003,-0.617376,0.841614,...,-0.392523,-0.603263,-0.356812,-0.438337,0.900496,0.810283,0.397917,0.396087,0.543076,1.054259
4,-0.481652,-0.539192,-0.552092,-0.510920,-1.485645,-1.333423,-0.957242,-0.817383,-1.244813,-1.048940,...,-0.704506,-0.920947,-0.768867,-0.651506,-2.123050,-1.325742,-1.212947,-1.322932,-1.658956,-1.394429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,-0.411653,-0.469401,-0.439884,-0.473348,0.481362,-0.525088,-0.719545,-0.710591,-0.372342,-0.430453,...,-0.533759,-0.775205,-0.557510,-0.545645,0.249566,-0.856308,-0.830988,-0.899219,-0.354968,-0.862154
110,-1.403884,-1.499974,-1.276572,-1.192594,4.858910,2.302355,0.119907,0.112594,2.118843,4.713376,...,-1.256799,-1.548129,-1.155950,-1.041834,2.512529,0.556175,-0.313428,-0.188239,0.224950,2.273592
111,-0.166658,-0.099512,-0.149838,-0.269979,0.705296,0.205677,-0.027771,0.146358,-0.004790,-0.291549,...,-0.303988,0.223700,-0.294683,-0.363239,0.441787,0.004236,0.328845,0.466451,-0.391420,-0.417849
112,-0.881227,-0.511275,-0.863309,-0.841320,1.680492,0.059754,-0.607824,-0.144963,0.544682,2.482142,...,-0.959573,-0.834157,-0.941851,-0.841151,1.464052,-0.337320,-0.717787,-0.300821,-0.202533,1.805902


In [32]:
df_mm_test = pd.DataFrame(x_test_mm_sc_data, columns=list(c.feature_names))
df_mm_test

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,0.276644,0.293879,0.260574,0.164016,0.339959,0.069873,0.004358,0.014533,0.345070,0.187596,...,0.221032,0.314741,0.196489,0.116700,0.159533,0.031182,0.004456,0.030144,0.223331,0.060803
1,0.384357,0.170105,0.369315,0.249324,0.392310,0.179191,0.107966,0.175348,0.249729,0.200044,...,0.370635,0.168184,0.356588,0.214242,0.288291,0.162727,0.171805,0.429897,0.366833,0.175981
2,0.378428,0.187014,0.375822,0.241348,0.657869,0.351267,0.233505,0.351093,0.572048,0.294824,...,0.333730,0.177006,0.329756,0.190464,0.328617,0.268228,0.207987,0.480069,0.376812,0.194740
3,0.280103,0.286101,0.281252,0.162402,0.597046,0.349733,0.187840,0.252187,0.314735,0.405765,...,0.255952,0.288275,0.250880,0.138136,0.509728,0.341786,0.286102,0.483505,0.395581,0.316542
4,0.269233,0.246534,0.251681,0.158462,0.249158,0.046500,0.031443,0.084443,0.223185,0.123389,...,0.197222,0.233068,0.175247,0.101854,0.020092,0.012504,0.017867,0.097320,0.079829,0.028073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,0.281091,0.256679,0.270841,0.164443,0.544911,0.175633,0.074813,0.104722,0.350488,0.215768,...,0.229365,0.258395,0.214042,0.119872,0.404316,0.084870,0.081470,0.192509,0.266809,0.090778
110,0.113000,0.106865,0.127973,0.049941,1.203106,0.627323,0.227976,0.261034,0.713976,0.984058,...,0.093254,0.124075,0.104198,0.035419,0.770782,0.302614,0.167652,0.352234,0.349964,0.460186
111,0.322595,0.310450,0.320367,0.196819,0.578582,0.292375,0.201031,0.267445,0.404117,0.236515,...,0.272619,0.431986,0.262284,0.150918,0.435444,0.217529,0.274601,0.499313,0.261582,0.143120
112,0.201542,0.250592,0.198540,0.105863,0.725209,0.269063,0.095197,0.212127,0.484290,0.650797,...,0.149206,0.248150,0.143496,0.069576,0.600990,0.164876,0.100319,0.326942,0.288667,0.405090


In [33]:
data={
    "emp_id":[1,2,3,4,5],
    "emp_name":["SG", "AG", "TG", "BG", "OG"],
    "emp_salary":[20000,30000,40000,50000,60000],
    "emp_fb":["G", "VG", "B", "VB", "AVG"]
}
df1=pd.DataFrame(data)
df1

,emp_id,emp_name,emp_salary,emp_fb
0,1,SG,20000,G
1,2,AG,30000,VG
2,3,TG,40000,B
3,4,BG,50000,VB
4,5,OG,60000,AVG


In [34]:
df1["emp_fb"].value_counts()


,count
emp_fb,
G,1
VG,1
B,1
VB,1
AVG,1


In [35]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [36]:
One=OneHotEncoder(sparse_output=False)
L=LabelEncoder()


In [37]:
df1['emp_fb']=L.fit_transform(df1['emp_fb'])

In [38]:
df1

,emp_id,emp_name,emp_salary,emp_fb
0,1,SG,20000,2
1,2,AG,30000,4
2,3,TG,40000,1
3,4,BG,50000,3
4,5,OG,60000,0
